project:
  type: website
  output-dir: docs

website:
  title: "Electrial Pulse Stimulation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px
      gutter-width: 1rem
    theme:
      - cosmo
      - html/custom.scss
    embed-resources: true
    toc: true
    highlight-style: night

tables:
      style: Table
      caption:
        pre: "Table "
        sep: " -- "

